# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY_COM", ""))'
  skip_cleanup: true
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
